#
# █▄░█ █▀▀ ▄▀█ █▀█ █▀▄▀█ ▄▀█ █▄░█ ▄▀█ █▀▀ █▀▀ █▀█
# █░▀█ ██▄ █▀█ █▀▄ █░▀░█ █▀█ █░▀█ █▀█ █▄█ ██▄ █▀▄
#
#                           (By MilkyWay for everyone)
#
#   ◆ Нашёл баг/ошибку/недочёт? Пиши мне об проблеме в тг - @vkusniy_milkyway
#   ◆ Поддержи, пожалуйста, плагин оценкой и подпишись на мой тгк - @GornaSquad
#                           Мне будет очень приятно :)
#

# Основные настройки плагина
settings:

  # Настройка радиуса поиска для команды /near, если у игрока нет специального права
  default-radius-without-permission:
    # Радиус поиска в блоках (по умолчанию 100). Используется, если не задано право nearmanager.near-radius.<Радиус>
    radius: 100

  # Настройка задержки для команды /near
  # Для обхода данной задержки нужно использовать пермишен "nearmanager.near.bypass-cooldown"
  near-cooldown:
    # Включить задержку для команды /near (true/false)
    enabled: true
    # Время задержки (В секундах)
    time: 5

  # Настройка скрытия игроков в невидимости, отображаемых в /near (или в ванише, например, через CMI или Essentials)
  # Для обхода скрытия, чтобы в невидимости игроки были видны, нужно использовать пермишен "nearmanager.near.bypass-vanish"
  hide-vanished-players:
    # Включить скрытие игроков в невидимости (true/false)
    enabled: true

  # Настройка скрытия определённых игроков по никнеймам, отображаемых в /near
  ignored-players:
    # Включить скрытие указанных игроков (true/false)
    enabled: false
    # Список никнеймов игроков, которые не будут отображаться в /near
    players:
      - "Player1"
      - "Player2"
      - "Player3"
      - "_Player3"

  # Настройка радиуса команды /near для групп LuckPerms
  # Позволяет задавать радиус поиска для групп через LuckPerms
  # Hазрешения (nearmanager.near-radius.<Радиус>) имеют приоритет над группами
  near-radius-groups:
    # Включить настройку радиуса для групп (true/false)
    enabled: true
    # Список групп и их радиусов поиска
    # Формат: <Название группы>: <Радиус в блоках>
    # Пример:
    #   default: 100
    #   vip: 200
    #   admin: 500
    groups:
      default: 200
      vip: 300
      admin: 1000

  # Настройка возможности игрокам выбирать радиус для команды /near
  custom-radius-selection:
    # Включить возможность выбора радиуса (true/false)
    enabled: true
    # Минимальный радиус, который можно указать
    min-radius: 0
    # Максимальный радиус, который можно указать
    max-radius: 100000

  # Настройка ограничения количества игроков, отображаемых в /near
  max-players-in-radius:
    # Включить ограничение количества отображаемых игроков (true/false)
    enabled: true
    # Максимальное количество игроков в списке (по умолчанию 10)
    max: 10

  # Настройки боссбара для отслеживания выбранного игрока
  bossbar:
    # Включить или выключить функциональность боссбара (true/false)
    # Если false, команда /nm bossbar и кнопка [Боссбар] не работают
    enabled: true
    # Цвет боссбара. Доступные значения: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
    color: YELLOW
    # Стиль боссбара. Доступные значения: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
    style: SEGMENTED_6
    # Текст, отображаемый в боссбаре. Поддерживает HEX-цвета (#RRGGBB) и плейсхолдеры:
    # {player} - имя отслеживаемого игрока, {distance} - расстояние, {direction} - направление
    text: "&#FFFF00◆ &fИгрок &#FFFF00{player} &fнаходится в &#FFFF00{distance} &fблока(ах) &#FFFF00({direction})"
    # Частота обновления боссбара в тиках (20 тиков = 1 секунда). Меньше значение = чаще обновление
    update-interval: 5
    # Минимальное расстояние, при котором боссбар исчезает
    min-distance:
      # Включить проверку минимального расстояния (true/false)
      enabled: true
      # Расстояние в блоках, при котором боссбар исчезает (если игрок ближе)
      distance: 15
    # Максимальное расстояние, при котором боссбар исчезает
    max-distance:
      # Включить проверку максимального расстояния (true/false)
      enabled: true
      # Расстояние в блоках, при котором боссбар исчезает (если игрок дальше)
      distance: 150
    # Таймер автоматического отключения боссбара
    timeout:
      # Включить таймер автоматического отключения (true/false)
      enabled: true
      # Время в секундах, после которого боссбар исчезает
      time: 120
    # Настройка заполненности боссбара
    progress:
      # Включить динамическую заполненность боссбара (true/false)
      enabled: true
      # Режим заполненности: "distance" (по расстоянию) или "time" (по времени)
      # distance: заполненность зависит от расстояния до игрока
      # time: заполненность уменьшается по таймеру (используется timeout.time)
      mode: "distance"
      # Минимальная заполненность боссбара в процентах (0-100)
      # Значение, когда игрок находится на минимальном расстоянии (или 0 блоков)
      min-progress: 0
      # Максимальная заполненность боссбара в процентах (0-100)
      # Значение при начальном расстоянии или дальше
      max-progress: 100
      # Использовать минимальное расстояние (min-distance.distance) как 0% заполненности (true/false)
      # Если true, 0% = min-distance.distance; если false, 0% = 0 блоков
      use-min-distance-as-zero: true

  # Символы для указания направления к игрокам в /near и боссбаре
  directions:
    # Символ для севера
    north: "⬆"
    # Символ для северо-востока
    northeast: "⬈"
    # Символ для востока
    east: "➡"
    # Символ для юго-востока
    southeast: "⬊"
    # Символ для юга
    south: "⬇"
    # Символ для юго-запада
    southwest: "⬋"
    # Символ для запада
    west: "⬅"
    # Символ для северо-запада
    northwest: "⬉"

# Сообщения плагина
messages:
  near-messages:
    no-players: "&#FB8808◆ &fПо близости вас &#FB8808нет &fигроков..."
    near:
      - " "
      - " &#FFFF00◆ &fИгроки в радиусе &#FFFF00{radius} &fблока(ах) от вас:"
      - ""
      - "  {near-players}"
      - " "
    near-players: "&#FFFF00◆ &f{number}. &#FFFF00{player} &f- в &#FFFF00{blocks} &fблока(ов) &#FFFF00({direction}) {open-inventory-button} {teleport-button} {bossbar-button}"
    too-many-players: "&#FB8808◆ &fВ вашем радиусе &#FB8808слишком &fмного игроков..."
    invalid-radius: "&#FB8808◆ Стоп! &fВведите &#FB8808корректное &fчисло для радиуса!"
    cooldown: "&#FB8808◆ &fПодождите &#FB8808{time} сек.&f, чтобы использовать команду снова!"
    invalid-max-radius: "&#FB8808◆ Стоп! &fМаксимальный радиус для неара &#FB8808{max-radius} &fблоков!"
    invalid-min-radius: "&#FB8808◆ Стоп! &fМинимальный радиус для неара &#FB8808{min-radius} &fблоков!"
    # Чтобы увидеть данную кнопку, нужно иметь пермишен "nearmanager.near-buttons.open-inventory"
    open-inventory-button:
      text: "&f| &#FFFF00[Инв]"
      hover-text: "&#FFFF00◆ &fНажмите, чтобы &#FFFF00открыть &fинвентарь игрока"
      click-command: "/invsee {player}"
    # Чтобы увидеть данную кнопку, нужно иметь пермишен "nearmanager.near-buttons.teleport"
    teleport-button:
      text: "&#FFFF00[Тп]"
      hover-text: "&#FFFF00◆ &fНажмите, чтобы &#FFFF00телепортироваться &fк игроку"
      click-command: "/tp {player}"
    # Чтобы увидеть данную кнопку, нужно иметь пермишен "nearmanager.near-buttons.bossbar"
    bossbar-button:
      text: "&#FFFF00[Боссбар]"
      hover-text: "&#FFFF00◆ &fНажмите, чтобы &#FFFF00активировать &fбоссбар"
      click-command: "nm bossbar {player} on"
  plugin-messages:
    no-permission: "&#FB8808▶ &fНедостаточно &#FB8808прав на использование &fэтой команды!"
    no-console: "&#FB8808▶ Стоп! Вы &#FB8808не можете &fпрописать эту команду из консоли!"
    reload: "&#FFFF00◆ &#FFF000N&#FFE900e&#FFE100a&#FFDA00r&#FFD200M&#FFCB00a&#FFC300n&#FFBC00a&#FFB400g&#FFAD00e&#FFA500r &f┃ Плагин успешно перезагружен за &#FFFF00{time} мс."
    bossbar-messages:
      already-active: "&#FB8808◆ &fУ вас &#FB8808уже есть &fактивный боссбар!"
      player-not-found: "&#FB8808◆ &fИгрок &#FB8808{player} &fне найден или не в сети!"
      close: "&#FB8808◆ &fВы &#FB8808слишком близко &fк игроку &#FB8808{player} &fдля боссбара!"
      too-far: "&#FB8808◆ &fВы &#FB8808слишком далеко &fот игрока &#FB8808{player} &fдля боссбара!"
      gone-close: "&#FB8808◆ &fБоссбар &#FB8808исчез&f, вы подошли &#FB8808слишком близко &fк игроку..."
      gone-far: "&#FB8808◆ &fБоссбар &#FB8808исчез&f, вы отошли &#FB8808слишком далеко &fот игрока..."
      self-target: "&#FB8808◆ &fВы &#FB8808не можете &fактивировать боссбар для &#FB8808себя!"
      activated: "&#FFFF00◆ &fБоссбар для игрока &#FFFF00{player} &fвключён!"
      turned-off: "&#FFFF00◆ &fБоссбар для игрока &#FFFF00{player} &fвыключен!"
      already-off: "&#FB8808◆ &fБоссбар для игрока &#FB8808{player} &fуже выключен!"
      timeout: "&#FB8808◆ &fБоссбар для игрока &#FB8808{player} &fисчез, так как время вышло..."
      player-offline: "&#FB8808◆ &fБоссбар исчез, так как игрок &#FB8808{player} &fвышел из сети..."
      player-changed-world: "&#FB8808◆ &fБоссбар исчез, так как игрок &#FB8808{player} &fпереместился в другой мир..."
      self-changed-world: "&#FB8808◆ &fБоссбар исчез, так как вы переместились в другой мир!"
    help-for-players:
      - " "
      - " &#FFFF00▶ &fКоманды плагина:"
      - " "
      - "  &#FFFF00◆ /near &f- Просмотр игроков по близости"
      - " "
    help-for-admins:
      - " "
      - " &#FFFF00▶ &fКоманды плагина:"
      - " "
      - "  &#FFFF00◆ /near &f- Просмотров игроков по близости"
      - "  &#FFFF00◆ /nm reload &f- Перезагрузить плагин"
      - "  &#FFFF00◆ /nm bossbar <Никнейм> (on/off) (-nodist) &f- Активировать боссбар (-nodist - Игнорирует дистанцию)"
      - " "